global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend1'
    static_configs:
      - targets: ['backend1:8000']

  - job_name: 'backend2'
    static_configs:
      - targets: ['backend2:8000']

  - job_name: 'celery'
    static_configs:
      - targets: ['celery:8000'] # 若有暴露 Prometheus metrics

  - job_name: 'monitor'
    static_configs:
      - targets: ['backend1:8000']  # 若你把 Evidently 的 Prometheus Exporter 綁在 backend

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  # 監控 Node Exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # 監控 cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://backend1:8000/docs
          - http://backend2:8000/docs
          - http://mlflow:5000
          - http://clickhouse:8123/ping
          - http://minio:9001
          - http://grafana:3000
          - http://prometheus:9090/-/ready
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
